package com.bot.chillburger.enums;

public enum BotState {
    START,
    CHOOSE_LANG,
    MAIN_SECTION,
    SELECT_CITY,
    CONTACT_ADMIN,
    MENU_SELECT_DELIVERY_TYPE,
    FIND_CLOSE_BRANCH,
    TAKE_AWAY_SELECT_TYPE,
    SELECT_INTERACTIVE_MENU, ADD_PRODUCT_MENU, ADD_TO_BASKET, SHOW_BASKET_STATE, SHARE_CONTACT
}
